version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: noah-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: webstore
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  postgres:
    image: postgres:15
    container_name: noah-postgres
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: noah-rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      retries: 10

  kong:
    image: kong:latest
    container_name: noah-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    volumes:
      - ./backend/gateway/kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"

  inventory_sync:
    build: ./backend/inventory_sync
    container_name: noah-inventory_sync
    volumes:
      - ./docs:/app/input
      - ./processed:/app/processed
    depends_on:
      mysql: { condition: service_healthy }

  order_api:
    build: ./backend/order_api
    container_name: noah-order_api
    # ĐÃ XÓA PORTS ĐỂ TRÁNH XUNG ĐỘT VÀ ĐÚNG YÊU CẦU BẢO MẬT
    depends_on:
      mysql: { condition: service_healthy }
      rabbitmq: { condition: service_healthy }

  worker:
    build: ./backend/middleware_worker
    container_name: noah-worker
    depends_on:
      rabbitmq: { condition: service_healthy }
      postgres: { condition: service_started }

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    container_name: noah-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./docs:/data
    depends_on:
      mysql: { condition: service_healthy }